
build-linux-native:
  stage: build
  image: gcc
  tags:
      - linux
      - docker
      - x64
  before_script:
    - apt update && apt -y install make autoconf cmake 
    - apt -y install libboost1.74-dev libboost-system-dev
  script:
    - cmake -DBUILD_ASIO_HTTP_TESTS=ON .
    - make
    - ctest

